// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Core.Data;

#nullable disable

namespace TradingJournal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906164049_FixOnTrade")]
    partial class FixOnTrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProfitLoss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("ScreenshotImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ScreenshotLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
