// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Core.Data;

#nullable disable

namespace TradingJournal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026141003_CleanRecoverySchema")]
    partial class CleanRecoverySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.RecoveryAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("InvestedUSDT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("RecoveryCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryCaseId");

                    b.ToTable("RecoveryAllocations", (string)null);
                });

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.RecoveryCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("InvestedUSDT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecoveryCases", (string)null);
                });

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ProfitLoss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("ScreenshotImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ScreenshotLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.RecoveryAllocation", b =>
                {
                    b.HasOne("TradingJournal.Core.Data.Entities.RecoveryCase", "RecoveryCase")
                        .WithMany("Allocations")
                        .HasForeignKey("RecoveryCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecoveryCase");
                });

            modelBuilder.Entity("TradingJournal.Core.Data.Entities.RecoveryCase", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
